@echo off
cd /d "%~dp0"
python CHECK_V4250_REGRESSION_SAFE_FUNCTIONAL_PROMOTION.py
if errorlevel 1 exit /b 1
python -m unittest CHECK_V4251_FUNCTIONAL_TRANSACTIONS CHECK_V4252_DURABLE_FUNCTIONAL_PROGRESS CHECK_V4253_PROJECT_UPLOADS CHECK_V4253_JOB_LIFECYCLE CHECK_V4254_WORKFLOW_CONVERGENCE CHECK_V4255_MODEL_PROTOCOL -v
exit /b %errorlevel%
